spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://db:5432/email
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true